name: Windows - Litemanager

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://www.gitlab.com/chamod12/1m_win-10-github_rdp/-/raw/main/Downloads.bat"  -outfile "Do cmd/c  Downloads.bat
          cmd /c Downloads.bat
          
      - name: Connect to Litemanager
        run: cmd /c show.bat

      - name: Time Counter
        run: cmd  /c  loop.bat
